import {
  hashApprovalToken,
  constantTimeEqual,
  secureId,
  secureToken,
} from '../../security/secure-approval.js';

import type {
  ActionPreview,
} from './action-preview.js';

import {
  hashActionPreview,
} from './action-preview.js';

export type ApprovalStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'expired';

export interface ApprovalDecision {
  readonly status: ApprovalStatus;
  readonly approvalId: string;
  readonly previewId: string;
  readonly actionHash: string;
  readonly deviceId: string;
  readonly requestId: string;
  readonly issuedAt: string;
  readonly expiresAt: string;
  readonly token?: string;
}

export interface ApprovalGateRequest {
  readonly preview: ActionPreview;
  readonly deviceId: string;
  readonly requestId: string;
  readonly now: string;
  readonly ttlMs?: number;
}

export interface ApprovalGate {
  request(
    input: ApprovalGateRequest,
  ): ApprovalDecision;

  approve(
    approvalId: string,
  ): ApprovalDecision;

  reject(
    approvalId: string,
  ): ApprovalDecision;

  consume(
    input: {
      readonly approvalId: string;
      readonly token: string;
      readonly preview: ActionPreview;
      readonly deviceId: string;
      readonly requestId: string;
      readonly now: string;
    },
  ): ApprovalDecision;

  get(
    approvalId: string,
  ): ApprovalDecision | undefined;
}

interface InternalApproval {
  readonly status: ApprovalStatus;
  readonly approvalId: string;
  readonly previewId: string;
  readonly actionHash: string;
  readonly deviceId: string;
  readonly requestId: string;
  readonly issuedAt: string;
  readonly expiresAt: string;
  readonly tokenHash: string;
  readonly consumed: boolean;
}

export interface InMemoryApprovalGateOptions {
  readonly now?: () => string;
  readonly defaultTtlMs?: number;
}

function required(
  value: string,
  field: string,
): string {
  const normalized =
    value.trim();

  if (!normalized) {
    throw new Error(
      `${field} is required.`,
    );
  }

  return normalized;
}

function parseTime(
  value: string,
): number {
  const timestamp =
    Date.parse(value);

  if (
    !Number.isFinite(
      timestamp,
    )
  ) {
    throw new Error(
      'Invalid approval timestamp.',
    );
  }

  return timestamp;
}

export class InMemoryApprovalGate
  implements ApprovalGate {
  private readonly approvals =
    new Map<
      string,
      InternalApproval
    >();

  private readonly now:
    () => string;

  private readonly defaultTtlMs:
    number;

  public constructor(
    options: InMemoryApprovalGateOptions = {},
  ) {
    this.now =
      options.now ??
      (() =>
        new Date().toISOString());

    this.defaultTtlMs =
      options.defaultTtlMs ??
      5 * 60_000;

    if (
      !Number.isFinite(
        this.defaultTtlMs,
      ) ||
      this.defaultTtlMs <= 0
    ) {
      throw new Error(
        'Approval TTL must be positive.',
      );
    }
  }

  public request(
    input: ApprovalGateRequest,
  ): ApprovalDecision {
    const deviceId =
      required(
        input.deviceId,
        'Approval device id',
      );

    const requestId =
      required(
        input.requestId,
        'Approval request id',
      );

    const issuedMs =
      parseTime(
        input.now,
      );

    const ttlMs =
      input.ttlMs ??
      this.defaultTtlMs;

    if (
      !Number.isFinite(
        ttlMs,
      ) ||
      ttlMs <= 0
    ) {
      throw new Error(
        'Approval TTL must be positive.',
      );
    }

    /*
     * The token generated at request time is stored only as
     * a hash. The raw executable token is intentionally not
     * exposed while the approval is still pending.
     *
     * A new raw token is generated by approve() only after
     * the approval transitions to "approved".
     */
    const pendingToken =
      secureToken();

    const internal:
      InternalApproval =
      {
        status:
          'pending',

        approvalId:
          secureId(),

        previewId:
          input.preview.id,

        actionHash:
          hashActionPreview(
            input.preview,
          ),

        deviceId,

        requestId,

        issuedAt:
          new Date(
            issuedMs,
          ).toISOString(),

        expiresAt:
          new Date(
            issuedMs + ttlMs,
          ).toISOString(),

        tokenHash:
          hashApprovalToken(
            pendingToken,
          ),

        consumed:
          false,
      };

    this.approvals.set(
      internal.approvalId,
      internal,
    );

    return this.publicDecision(
      internal,
    );
  }

  public approve(
    approvalId: string,
  ): ApprovalDecision {
    const current =
      this.requireApproval(
        approvalId,
      );

    if (
      current.status !==
      'pending'
    ) {
      return this.publicDecision(
        current,
      );
    }

    /*
     * Expiration must be evaluated against the injected clock,
     * not Date.now(), so runtime/tests can share deterministic
     * time.
     */
    const now =
      parseTime(
        this.now(),
      );

    if (
      parseTime(
        current.expiresAt,
      ) <= now
    ) {
      const expired:
        InternalApproval =
        {
          ...current,
          status:
            'expired',
        };

      this.approvals.set(
        approvalId,
        expired,
      );

      return this.publicDecision(
        expired,
      );
    }

    const token =
      secureToken();

    const approved:
      InternalApproval =
      {
        ...current,

        status:
          'approved',

        tokenHash:
          hashApprovalToken(
            token,
          ),
      };

    this.approvals.set(
      approvalId,
      approved,
    );

    return {
      ...this.publicDecision(
        approved,
      ),
      token,
    };
  }

  public reject(
    approvalId: string,
  ): ApprovalDecision {
    const current =
      this.requireApproval(
        approvalId,
      );

    if (
      current.status !==
      'pending'
    ) {
      return this.publicDecision(
        current,
      );
    }

    const now =
      parseTime(
        this.now(),
      );

    if (
      parseTime(
        current.expiresAt,
      ) <= now
    ) {
      const expired:
        InternalApproval =
        {
          ...current,
          status:
            'expired',
        };

      this.approvals.set(
        approvalId,
        expired,
      );

      return this.publicDecision(
        expired,
      );
    }

    const rejected:
      InternalApproval =
      {
        ...current,
        status:
          'rejected',
      };

    this.approvals.set(
      approvalId,
      rejected,
    );

    return this.publicDecision(
      rejected,
    );
  }

  public consume(
    input: {
      readonly approvalId: string;
      readonly token: string;
      readonly preview: ActionPreview;
      readonly deviceId: string;
      readonly requestId: string;
      readonly now: string;
    },
  ): ApprovalDecision {
    const current =
      this.requireApproval(
        input.approvalId,
      );

    const now =
      parseTime(
        input.now,
      );

    /*
     * The final execution boundary re-checks the TTL even when
     * the approval was granted earlier.
     */
    if (
      parseTime(
        current.expiresAt,
      ) <= now
    ) {
      const expired:
        InternalApproval =
        {
          ...current,
          status:
            'expired',
        };

      this.approvals.set(
        input.approvalId,
        expired,
      );

      throw new Error(
        'Approval has expired.',
      );
    }

    if (
      current.status !==
      'approved'
    ) {
      throw new Error(
        `Approval is not executable: ${current.status}.`,
      );
    }

    if (
      current.consumed
    ) {
      throw new Error(
        'Approval has already been consumed.',
      );
    }

    const suppliedToken =
      required(
        input.token,
        'Approval token',
      );

    const suppliedHash =
      hashApprovalToken(
        suppliedToken,
      );

    if (
      !constantTimeEqual(
        current.tokenHash,
        suppliedHash,
      )
    ) {
      throw new Error(
        'Approval token is invalid.',
      );
    }

    const deviceId =
      required(
        input.deviceId,
        'Approval device id',
      );

    if (
      current.deviceId !==
      deviceId
    ) {
      throw new Error(
        'Approval device mismatch.',
      );
    }

    const requestId =
      required(
        input.requestId,
        'Approval request id',
      );

    if (
      current.requestId !==
      requestId
    ) {
      throw new Error(
        'Approval request mismatch.',
      );
    }

    if (
      current.previewId !==
      input.preview.id
    ) {
      throw new Error(
        'Approval preview mismatch.',
      );
    }

    const previewHash =
      hashActionPreview(
        input.preview,
      );

    if (
      current.actionHash !==
      previewHash
    ) {
      throw new Error(
        'Approval action hash mismatch.',
      );
    }

    /*
     * Mark the approval as consumed and destroy the token hash.
     * This guarantees one-shot execution.
     */
    const consumed:
      InternalApproval =
      {
        ...current,
        consumed:
          true,
        tokenHash:
          '',
      };

    this.approvals.set(
      input.approvalId,
      consumed,
    );

    return this.publicDecision(
      consumed,
    );
  }

  public get(
    approvalId: string,
  ):
    | ApprovalDecision
    | undefined {
    const current =
      this.approvals.get(
        approvalId,
      );

    if (
      current ===
      undefined
    ) {
      return undefined;
    }

    return this.publicDecision(
      current,
    );
  }

  private requireApproval(
    approvalId: string,
  ): InternalApproval {
    const id =
      required(
        approvalId,
        'Approval id',
      );

    const approval =
      this.approvals.get(
        id,
      );

    if (
      approval ===
      undefined
    ) {
      throw new Error(
        'Approval not found.',
      );
    }

    return approval;
  }

  private publicDecision(
    approval: InternalApproval,
  ): ApprovalDecision {
    return {
      status:
        approval.status,

      approvalId:
        approval.approvalId,

      previewId:
        approval.previewId,

      actionHash:
        approval.actionHash,

      deviceId:
        approval.deviceId,

      requestId:
        approval.requestId,

      issuedAt:
        approval.issuedAt,

      expiresAt:
        approval.expiresAt,
    };
  }
}