create table if not exists public.dj_reasoning_runs (
  id bigint generated always as identity primary key,
  device_id text not null,
  track_id text not null,
  reasoning_id uuid not null unique,
  engine_version text not null,
  model text not null,
  provider text not null,
  request text not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_dj_reasoning_runs_track
  on public.dj_reasoning_runs (device_id, track_id, created_at desc);

create index if not exists idx_dj_reasoning_runs_reasoning_id
  on public.dj_reasoning_runs (reasoning_id);

comment on table public.dj_reasoning_runs is
  'Durable history of structured DJ reasoning results generated by the Electron intelligence layer.';

create or replace function public.save_dj_reasoning_run(
  p_device_id text,
  p_track_id text,
  p_reasoning_id uuid,
  p_engine_version text,
  p_model text,
  p_provider text,
  p_request text,
  p_result jsonb
)
returns public.dj_reasoning_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.dj_reasoning_runs;
begin
  if nullif(trim(p_device_id), '') is null then
    raise exception 'device_id_required';
  end if;

  if nullif(trim(p_track_id), '') is null then
    raise exception 'track_id_required';
  end if;

  if p_reasoning_id is null then
    raise exception 'reasoning_id_required';
  end if;

  if nullif(trim(p_engine_version), '') is null then
    raise exception 'engine_version_required';
  end if;

  if nullif(trim(p_model), '') is null then
    raise exception 'model_required';
  end if;

  if nullif(trim(p_provider), '') is null then
    raise exception 'provider_required';
  end if;

  if nullif(trim(p_request), '') is null then
    raise exception 'request_required';
  end if;

  insert into public.dj_reasoning_runs (
    device_id,
    track_id,
    reasoning_id,
    engine_version,
    model,
    provider,
    request,
    result
  )
  values (
    trim(p_device_id),
    trim(p_track_id),
    p_reasoning_id,
    trim(p_engine_version),
    trim(p_model),
    trim(p_provider),
    trim(p_request),
    coalesce(p_result, '{}'::jsonb)
  )
  on conflict (reasoning_id)
  do update set
    engine_version = excluded.engine_version,
    model = excluded.model,
    provider = excluded.provider,
    request = excluded.request,
    result = excluded.result
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.save_dj_reasoning_run(
  text, text, uuid, text, text, text, text, jsonb
) from public;
