create table if not exists public.copilot_action_audit (
  id bigint generated by default as identity primary key,
  action_id text not null,
  approval_id text null,
  device_id text not null,
  request_id text not null,
  action_type text not null,
  action_hash text not null,
  status text not null,
  timestamp timestamptz not null,
  error text null,
  result_metadata jsonb null,
  created_at timestamptz not null default now(),

  constraint copilot_action_audit_status_check
    check (
      status in (
        'requested',
        'previewed',
        'approved',
        'rejected',
        'executed',
        'failed',
        'expired'
      )
    ),

  constraint copilot_action_audit_action_id_check
    check (length(trim(action_id)) > 0),

  constraint copilot_action_audit_device_id_check
    check (length(trim(device_id)) > 0),

  constraint copilot_action_audit_request_id_check
    check (length(trim(request_id)) > 0),

  constraint copilot_action_audit_action_type_check
    check (length(trim(action_type)) > 0),

  constraint copilot_action_audit_action_hash_check
    check (length(trim(action_hash)) > 0)
);

create index if not exists copilot_action_audit_device_time_idx
on public.copilot_action_audit (
  device_id,
  timestamp desc
);

create index if not exists copilot_action_audit_action_idx
on public.copilot_action_audit (
  action_id,
  timestamp asc
);

alter table public.copilot_action_audit
  enable row level security;

comment on table public.copilot_action_audit is
  'Audit trail for Copilot DJ actions and approval lifecycle.';

comment on column public.copilot_action_audit.result_metadata is
  'Non-sensitive execution metadata only; never store tokens or secrets.';
